/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { PatternrevealError } from "./patternrevealerror.js";

/**
 * This response is sent when a request conflicts with the current state of the server.
 */
export type ConflictErrorData = {
  error: models.ConflictError;
};

/**
 * This response is sent when a request conflicts with the current state of the server.
 */
export class ConflictError extends PatternrevealError {
  error: models.ConflictError;

  /** The original data that was passed to this error instance. */
  data$: ConflictErrorData;

  constructor(
    err: ConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ConflictError";
  }
}

/** @internal */
export const ConflictError$inboundSchema: z.ZodType<
  ConflictError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.ConflictError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ConflictError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
