/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { PatternrevealError } from "./patternrevealerror.js";

/**
 * This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
 */
export type InviteExpiredErrorData = {
  error: models.InviteExpiredError;
};

/**
 * This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
 */
export class InviteExpiredError extends PatternrevealError {
  error: models.InviteExpiredError;

  /** The original data that was passed to this error instance. */
  data$: InviteExpiredErrorData;

  constructor(
    err: InviteExpiredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "InviteExpiredError";
  }
}

/** @internal */
export const InviteExpiredError$inboundSchema: z.ZodType<
  InviteExpiredError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.InviteExpiredError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InviteExpiredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
