/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as models from "../index.js";
import { PatternrevealError } from "./patternrevealerror.js";

/**
 * The user has sent too many requests in a given amount of time ("rate limiting")
 */
export type RateLimitExceededErrorData = {
  error: models.RateLimitExceededError;
};

/**
 * The user has sent too many requests in a given amount of time ("rate limiting")
 */
export class RateLimitExceededError extends PatternrevealError {
  error: models.RateLimitExceededError;

  /** The original data that was passed to this error instance. */
  data$: RateLimitExceededErrorData;

  constructor(
    err: RateLimitExceededErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "RateLimitExceededError";
  }
}

/** @internal */
export const RateLimitExceededError$inboundSchema: z.ZodType<
  RateLimitExceededError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => models.RateLimitExceededError$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RateLimitExceededError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
