/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A short code indicating the error code returned.
 */
export const InviteExpiredCode = {
  InviteExpired: "invite_expired",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type InviteExpiredCode = ClosedEnum<typeof InviteExpiredCode>;

export type InviteExpiredError = {
  /**
   * A short code indicating the error code returned.
   */
  code: InviteExpiredCode;
  /**
   * A human readable explanation of what went wrong.
   */
  message: string;
  /**
   * A link to our documentation with more details about this error code
   */
  docUrl?: string | undefined;
};

/** @internal */
export const InviteExpiredCode$inboundSchema: z.ZodNativeEnum<
  typeof InviteExpiredCode
> = z.nativeEnum(InviteExpiredCode);

/** @internal */
export const InviteExpiredError$inboundSchema: z.ZodType<
  InviteExpiredError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: InviteExpiredCode$inboundSchema,
  message: z.string(),
  doc_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
  });
});

export function inviteExpiredErrorFromJSON(
  jsonString: string,
): SafeParseResult<InviteExpiredError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InviteExpiredError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InviteExpiredError' from JSON`,
  );
}
