/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A short code indicating the error code returned.
 */
export const RateLimitExceededCode = {
  RateLimitExceeded: "rate_limit_exceeded",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type RateLimitExceededCode = ClosedEnum<typeof RateLimitExceededCode>;

export type RateLimitExceededError = {
  /**
   * A short code indicating the error code returned.
   */
  code: RateLimitExceededCode;
  /**
   * A human readable explanation of what went wrong.
   */
  message: string;
  /**
   * A link to our documentation with more details about this error code
   */
  docUrl?: string | undefined;
};

/** @internal */
export const RateLimitExceededCode$inboundSchema: z.ZodNativeEnum<
  typeof RateLimitExceededCode
> = z.nativeEnum(RateLimitExceededCode);

/** @internal */
export const RateLimitExceededError$inboundSchema: z.ZodType<
  RateLimitExceededError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: RateLimitExceededCode$inboundSchema,
  message: z.string(),
  doc_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
  });
});

export function rateLimitExceededErrorFromJSON(
  jsonString: string,
): SafeParseResult<RateLimitExceededError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RateLimitExceededError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RateLimitExceededError' from JSON`,
  );
}
