/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * A short code indicating the error code returned.
 */
export const UnauthorizedCode = {
  Unauthorized: "unauthorized",
} as const;
/**
 * A short code indicating the error code returned.
 */
export type UnauthorizedCode = ClosedEnum<typeof UnauthorizedCode>;

export type UnauthorizedError = {
  /**
   * A short code indicating the error code returned.
   */
  code: UnauthorizedCode;
  /**
   * A human readable explanation of what went wrong.
   */
  message: string;
  /**
   * A link to our documentation with more details about this error code
   */
  docUrl?: string | undefined;
};

/** @internal */
export const UnauthorizedCode$inboundSchema: z.ZodNativeEnum<
  typeof UnauthorizedCode
> = z.nativeEnum(UnauthorizedCode);

/** @internal */
export const UnauthorizedError$inboundSchema: z.ZodType<
  UnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: UnauthorizedCode$inboundSchema,
  message: z.string(),
  doc_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
  });
});

export function unauthorizedErrorFromJSON(
  jsonString: string,
): SafeParseResult<UnauthorizedError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnauthorizedError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnauthorizedError' from JSON`,
  );
}
