/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Plan = {
  Free: "free",
  Pro: "pro",
} as const;
export type Plan = ClosedEnum<typeof Plan>;

export const Role = {
  Owner: "OWNER",
  Member: "MEMBER",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type User = {
  role: Role;
};

export type WorkspaceSchema = {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  inviteCode: string | null;
  billingCycleStart: number;
  plan: Plan;
  totalReflections: number;
  usage: number;
  usageLimit: number;
  reflectionsUsage: number;
  reflectionsLimit: number;
  aiUsage: number;
  aiLimit: number;
  usersLimit: number;
  store: { [k: string]: any };
  users: Array<User>;
  createdAt: string;
  updatedAt: string;
  paddleCustomerId: string | null;
};

/** @internal */
export const Plan$inboundSchema: z.ZodNativeEnum<typeof Plan> = z.nativeEnum(
  Plan,
);

/** @internal */
export const Role$inboundSchema: z.ZodNativeEnum<typeof Role> = z.nativeEnum(
  Role,
);

/** @internal */
export const User$inboundSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z
  .object({
    role: Role$inboundSchema,
  });

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}

/** @internal */
export const WorkspaceSchema$inboundSchema: z.ZodType<
  WorkspaceSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  logo: z.nullable(z.string()).default(null),
  inviteCode: z.nullable(z.string()),
  billingCycleStart: z.number(),
  plan: Plan$inboundSchema,
  totalReflections: z.number(),
  usage: z.number(),
  usageLimit: z.number(),
  reflectionsUsage: z.number(),
  reflectionsLimit: z.number(),
  aiUsage: z.number(),
  aiLimit: z.number(),
  usersLimit: z.number(),
  store: z.record(z.any()),
  users: z.array(z.lazy(() => User$inboundSchema)),
  createdAt: z.string(),
  updatedAt: z.string(),
  paddleCustomerId: z.nullable(z.string()),
});

export function workspaceSchemaFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceSchema' from JSON`,
  );
}
